function params = detection_parameters_interface6(params)


%% setting up the figure, panels and buttons
fh = figure(...
                  'Units','characters',...
                  'NumberTitle','off',...
                  'MenuBar','none',...
                  'Toolbar','none',...
                  'Name','Select Detection/Quantification Parameters',...
                  'Position',[10 10 92 42],...
                  'Visible','off'); 
              
%% attach parameters to figure
% parameters are attached to the figure object
% this way they can be accessed by all Callback functions
setappdata(fh,'params', params);               

%% psf settings
hpsf = uipanel('parent',fh,'Title','PSF Width (Pix)','Units','characters',...
    'Position',[5 32 26 9]);
        
uicontrol('parent',hpsf,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','text','String','PSF sigma xy',...
            'Position',[1,5,15,1.5]);           
hsxy = uicontrol('parent',hpsf,'Tag','hsxy',...
            'Units','characters',...
            'Style','edit','String',num2str(params.psfSigma(1)),...
            'Position',[16,5,8,1.5]);   
        
if params.numDim ==3
    uicontrol('parent',hpsf,'Units','characters',...
                'HorizontalAlignment','left',...
                'Style','text','String','PSF sigma z',...
                'Position',[1,3,15,1.5]);       
    uicontrol('parent',hpsf,'Tag','hsz',...
                'Units','characters',...
                'Style','edit','String',num2str(params.psfSigma(2)),...
                'Position',[16,3,8,1.5]);  
end  

hpsfm = uicontrol('parent',hpsf,'Tag','hpsf_manual',...
            'Units','characters',...
            'Style','Radio',...
            'String','Set interactively',...
            'Position',[1,1,20,1.5]);
set(hpsfm,'Value',params.setPsfInteractively);        

%% Threshold Settings
hthresh = uipanel('parent',fh,'Title','Detection Threshold',...
    'Units','characters',...
    'Position',[32 32 50 9]);
        
uicontrol('parent',hthresh,'Units','characters',...
            'Style','text','String','Threshold Value :',...
            'HorizontalAlignment','left',...
            'Position',[1.5,4,17,1.5]);
uicontrol('parent',hthresh,'Units','characters',...
            'Tag','hthresh_level',...
            'Style','edit','String',num2str(params.threshLevel),...
            'Position',[14,4,8,1.5]);

hthm = uicontrol('parent',hthresh,'Tag','hthresh_manual',...
    'Units','characters',...
    'Tag','hthresh_manually',...
    'String','Set Interactively',...
    'Style','Radio',...
    'Position',[1.5,1,14,1.5]);
set(hthm,'Value',params.setThreshInteractively);         
        
hth = uibuttongroup('parent',hthresh,'Units','characters',...
        'Tag','hthresh_units',...
        'Title','Units',...
        'Position',[27 0.2 22 8]);
        habs = uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','Absolute',...
            'Tag','Absolute',...
            'Position',[1.5 5.2 20 1.5]); 
        hSD = uicontrol('parent',hth,'Style','Radio','Units','characters',...
            'String','Intensity S.D.',...
            'Tag','SD',...
            'Position',[1.5 3.7 20 1.5]);
        hAdaptive = uicontrol('parent',hth,'Style','Radio','Units','characters',...
             'String','Adaptive using masks',...
             'Tag','adaptive',...
             'Position',[1.5 2.2 20 1.5]);
        hLegacySD = uicontrol('parent',hth,'Style','Radio','Units','characters',...
             'String','Intensity S.D. (legacy)',...
             'Tag','legacySD',...
             'Position',[1.5 0.7 20 1.5]);
        
params.threshUnits        
if strcmp(params.threshUnits,'absolute')
    set(hth,'SelectedObject',habs);
elseif strcmp(params.threshUnits,'SD')  
    set(hth,'SelectedObject',hSD);
elseif strcmp(params.threshUnits,'adaptive')  
    set(hth,'SelectedObject',hAdaptive);  
    set(habs,'ForegroundColor',[0.5,0.5,0.5]);
    set(hSD,'ForegroundColor',[0.5,0.5,0.5]);
    set(hLegacySD,'ForegroundColor',[0.5,0.5,0.5]);
elseif strcmp(params.threshUnits,'legacySD')  
    set(hth,'SelectedObject',hLegacySD);
end       

%% Saving Settings
hsave = uipanel('parent',fh,'Title','Saving Settings',...
    'Units','characters',...
    'Position',[5 19 77 12.5]);

uicontrol('parent',hsave,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','Text','String','Saving Directory',...
            'Position',[1,9,74,1.5]);
uicontrol('parent',hsave,'Units','characters',...
            'Tag','hsave',...
            'Style','edit','String',num2str(params.saveDirName),...
            'Position',[1,7.5,74,1.5]);
        
hman = uicontrol('parent',hsave,'Units','characters',...
            'Tag','houtput_spot_img',...
            'Style','Radio','String','Output Image of Spots',...
            'HorizontalAlignment','left',...
            'Position',[1,5,20,1.5]);
        
if isprop(params,'outputSpotsImage')        
    set(hman,'Value',params.outputSpotsImage); 
end

hLegacy = uicontrol('parent',hsave,'Units','characters',...
            'Tag','hLegacy',...
            'Style','Radio','String','Legacy Formats?',...
            'HorizontalAlignment','left',...
            'Position',[1,1,20,1.5]);
        
if isprop(params,'useLegacyFormats')        
    set(hLegacy,'Value',params.useLegacyFormats); 
end

hautoSize = uicontrol('parent',hsave,'Units','characters',...
            'Tag','hautoSpotSize',...
            'Style','Radio','String','set spots size to PSF sigma',...
            'HorizontalAlignment','left',...
            'Position',[22,5,25,1.5]); 

if isprop(params,'autoSpotSize')        
    set(hautoSize,'Value',params.autoSpotSize); 
end        

uicontrol('parent',hsave,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','text','String','spot size xy',...
            'Position',[25,3,15,1.5]);   
        
hspotxy = uicontrol('parent',hsave,'Tag','hSpotSizexy',...
            'Units','characters',...
            'Style','edit','String',num2str(params.spotSize(1)),...
            'Position',[35,3,8,1.5]);   

if params.numDim ==3
    uicontrol('parent',hsave,'Units','characters',...
                'HorizontalAlignment','left',...
                'Style','text','String','spot size z',...
                'Position',[25,1,15,1.5]);       
    hspotz = uicontrol('parent',hsave,'Tag','hSpotSizez',...
                'Units','characters',...
                'Style','edit','String',num2str(params.spotSize(2)),...
                'Position',[35,1,8,1.5]); 
end       

hautoInt = uicontrol('parent',hsave,'Units','characters',...
            'Tag','hautoInt',...
            'Style','Radio','String','set spots intensity to measured brigthness',...
            'HorizontalAlignment','left',...
            'Position',[45,5,35,1.5]);         

if isprop(params,'autoSpotIntensity')        
    set(hautoInt,'Value',params.autoSpotIntensity); 
end     

uicontrol('parent',hsave,'Units','characters',...
            'HorizontalAlignment','left',...
            'Style','text','String','spot intensity',...
            'Position',[48,3,15,1.5]);   
        
hspotI = uicontrol('parent',hsave,'Tag','hSpotInt',...
            'Units','characters',...
            'Style','edit','String',num2str(params.spotIntensity),...
            'Position',[58,3,8,1.5]);  
        

%% Advanced Settings
hadv = uipanel('parent',fh,'Title','Advanced Parameters - Should not need to be modified',...
    'Units','characters',...
    'Position',[5 3.5 77 15]);

% detection parameters        
hdet = uipanel('parent',hadv,'Title','Detection',...
    'Units','characters',...
    'Position',[1 0.5 34 13]);        

uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','---- Hi pass filter ----',...
            'HorizontalAlignment','left',...
            'Position',[1,10,32,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Length Cutoff in PSF width units',...
            'HorizontalAlignment','left',...
            'Position',[1,7.25,18,3]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hfilter_nlo',...
            'Style','edit','String',num2str(params.filterLo),...
            'Position',[23,8.5,8,1.5]); 
        
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','----  Low pass filter ----',...
            'HorizontalAlignment','left',...
            'Position',[1,6,32,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Length Cutoff in pixels',...
            'HorizontalAlignment','left',...
            'Position',[1,3.25,18,3]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hfilter_nhi',...
            'Style','edit','String',num2str(params.filterHi),...
            'Position',[23,5,8,1.5]);        
 
%Minimum allowed distance between predetected spots (Pix)         
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Min Dist. between Spots (Pix)',...
            'HorizontalAlignment','left',...
            'Position',[0.5,2.5,30,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hROIsize',...
            'Style','edit','String',num2str(params.minDistBetweenSpots),...
            'Position',[23,2.5,8,1.5]); 
        
%Maximum number of predetected spots          
uicontrol('parent',hdet,'Units','characters',...
            'Style','Text','String','Max Spots Count',...
            'HorizontalAlignment','left',...
            'Position',[0.5,0.5,20,1.5]);
uicontrol('parent',hdet,'Units','characters',...
            'Tag','hmax_spots',...
            'Style','edit','String',num2str(params.maxSpots),...
            'Position',[23,0.5,8,1.5]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
% quantification parameters        
hquant =  uipanel('parent',hadv,'Title','Quantification',...
    'Units','characters',...
    'Position',[36 0.5 39 13]); 

%PSF type
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','PSF type',...
            'HorizontalAlignment','left',...
            'Position',[1,10,21,1.5]);
       
if params.numDim == 3
    htypemenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','htype',...
            'Style','popupmenu','String',...
            {'integratedGaussianStdZ',...
            'integratedGaussian',...
            'gaussian'},...
            'Position',[23,10.2,14,1.5]);
        
elseif params.numDim == 2
     htypemenu = uicontrol('parent',hquant,'Units','characters',...
             'Tag','htype',...
             'Style','popupmenu','String',...
             {'integratedGaussian',...
             'gaussian'},...
             'Position',[23,10.2,14,1.5]); 
end

if isprop(params,'psfType')
    switch params.psfType
        case 'integratedGaussian'
            set(htypemenu,'Value',ceil(params.numDim-1));
        case 'gaussian'
            set(htypemenu,'Value',ceil(params.numDim));
        case 'integratedGaussianStdZ' 
            set(htypemenu,'Value',1);
    end
end

%Method of quantification
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Quantification Method',...
            'HorizontalAlignment','left',...
            'Position',[1,8,21,1.5]);
        
if params.numDim == 3
    hmethmenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','hmethod',...
            'Style','popupmenu','String',...
            {'3DMaskFull',...
            '2DMaskOnLocalMaxProj',...
            '3DGaussianFit'},...
            'Position',[23,8.2,14,1.5]);
        
elseif params.numDim == 2
     hmethmenu = uicontrol('parent',hquant,'Units','characters',...
             'Tag','hmethod',...
             'Style','popupmenu','String',...
             {'2DGaussianMask',...
             '2DGaussianFit'},...
             'Position',[23,8.2,14,1.5]); 
end

if isprop(params,'fitMethod')
    switch params.fitMethod
        case '3DMaskFull'
            set(hmethmenu,'Value',1);
        case '2DMaskOnLocalMaxProjection'
            set(hmethmenu,'Value',2);
        case '3DGaussianFit'
            if params.numDim == 3
                set(hmethmenu,'Value',3);
            else
                set(hmethmenu,'Value',2);
            end
        case '2DGaussianMask'
            set(hmethmenu,'Value',1);
        case '2DGaussianFit'
            set(hmethmenu,'Value',2);        
    end
end

%background correction 
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Background correction method',...
            'HorizontalAlignment','left',...
            'Position',[1,6,24,1.5]);
        
hbgmenu = uicontrol('parent',hquant,'Units','characters',...
            'Tag','hbg_mode',...
            'Style','popupmenu','String',...
            {'localPlane',...
            'localMedian',...
            'globalMedian'},...
            'Position',[25,6,12,1.5]);
        
if isprop(params,'bgCorrectionMode')
    switch params.bgCorrectionMode
        case 'localPlane'
            set(hbgmenu,'Value',1);
        case 'localMedian'
            set(hbgmenu,'Value',2);
        case 'globalMedian' 
            set(hbgmenu,'Value',3);       
    end
end

%size of the fitted region
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Size of fitted region (units of PSF sigma)',...
            'HorizontalAlignment','left',...
            'Position',[1,4,27,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hcutsize',...
            'Style','edit','String',num2str(params.fittedRegionSize),...
            'Position',[28,4,8,1.5]); 

%size of the region used for local background subtraction       
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Background region thickness (Pix)',...
            'HorizontalAlignment','left',...
            'Position',[1,2.25,33,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hthickness',...
            'Style','edit','String',num2str(params.bgRegionThickness),...
            'Position',[28,2.25,8,1.5]); 
        
%convergence tolerance of the gaussian mask       
uicontrol('parent',hquant,'Units','characters',...
            'Style','Text','String','Max Iterations Number',...
            'HorizontalAlignment','left',...
            'Position',[1,0.5,29,1.5]);
uicontrol('parent',hquant,'Units','characters',...
            'Tag','hmaxcount',...
            'Style','edit','String',num2str(params.maxIterations),...
            'Position',[28,0.5,8,1.5]);
        
%% action buttons        
%next button
hnext = uicontrol('Parent',fh,'Units','characters',...
                    'Style','pushbutton',...
                    'String','next',...
                    'Position',[62,1,20,2]);
%cancel button
hcancel = uicontrol('Parent',fh,'Units','characters',...
                    'Style','pushbutton',...
                    'String','cancel',...
                    'Position',[5,1,20,2]);

%% Callbacks
set(hnext,'Callback',{@next,fh});                
set(hcancel,'Callback',{@cancel,fh});               
set(fh,'Visible','on');
set(fh, 'KeyPressFcn', {@onKeyPress,fh});

uiwait;

%% Housekeeping
params = getappdata(fh,'params');
close(fh);
clear('hsave','hpsf','hpsfm','hthresh','hthm','hth','hadv','hdet','hquant','hnext','hcancel');
return;
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function onKeyPress(src,eventdata,fh)
    if strcmp(eventdata.Key, 'return') || strcmp(eventdata.Key, 'enter')
        next(src,eventdata,fh);
    end
end

function next(src,eventdata,fh)
    p = getappdata(fh,'params');
    handles = guihandles(fh);
    
    % psf parameters
    p.psfSigma(1) = str2double(get(handles.hsxy,'String'));
    if p.numDim == 3
         p.psfSigma(2) = str2double(get(handles.hsz,'String'));
    end
    p.setPsfInteractively = get(handles.hpsf_manual,'Value');
    
    % threshold parameters
    str_thr = get(get(handles.hthresh_units,'SelectedObject'),'Tag');   
    if  strcmp(str_thr,'Absolute') 
        p.threshUnits = 'absolute';
    elseif strcmp(str_thr,'SD') 
        p.threshUnits = 'SD';
    elseif strcmp(str_thr,'legacySD') 
        p.threshUnits = 'legacySD';
    end
    p.threshLevel = str2double( get(handles.hthresh_level,'String') );
    p.setThreshInteractively = get(handles.hthresh_manually,'Value');
    
    % saving paramters
    p.saveDirName = get(handles.hsave,'String');
    p.outputSpotsImage  = get(handles.houtput_spot_img,'Value');
    p.autoSpotSize = get(handles.hautoSpotSize  ,'Value');
    p.useLegacyFormats = get(handles.hLegacy  ,'Value');
    p.spotSize(1) = str2double( get(handles.hSpotSizexy   ,'String') );
    if p.numDim == 3
        p.spotSize(1) = str2double( get(handles.hSpotSizez   ,'String') );
    end
    p.autoSpotIntensity = get(handles.hautoInt  ,'Value');
    p.spotIntensity = str2double( get(handles.hSpotInt   ,'String') );
    
    
    %advanced parameters
    %detection
    p.filterLo = str2double( get(handles.hfilter_nlo,'String') ); 
    p.filterHi = str2double( get(handles.hfilter_nhi,'String') ); 
    p.minDistBetweenSpots = str2double(get(handles.hROIsize,'String'));
    p.maxSpots = str2double( get(handles.hmax_spots,'String')); 
    
    % quantification
    psfTypes = get(handles.htype,'String');
    p.psfType = psfTypes{get(handles.htype,'Value')};
    
    method = get(handles.hmethod,'String');
    p.fitMethod = method{get(handles.hmethod,'Value')};
    
    bgstr = get(handles.hbg_mode,'String');
    p.bgCorrectionMode = bgstr{get(handles.hbg_mode,'Value')};
    
    p.fittedRegionSize = str2double(get(handles.hcutsize,'String')); 
    p.bgRegionThickness = str2double(get(handles.hthickness,'String'));
    p.maxIterations = str2double(get(handles.hmaxcount,'String'));
    
    setappdata(fh,'params',p);
    
    %% housekeeping
    clear('p','handles','method','bgstr');
    uiresume
end

function cancel(src,eventdata,fh)
p = getappdata(fh,'params');
p.fileProcessingMode = 'cancel';
setappdata(fh,'params',p);
clear('p');
uiresume
end


