function params = set_detection_mode2(params)

%% setting up the figure, panels and buttons
    fh = figure(...
                  'Units','characters',...
                  'MenuBar','none',...
                  'Toolbar','none',...
                  'Name','Select File Mode',...
                  'NumberTitle','off',...
                  'Position',[50 20 80 26],...
                  'Visible','off'); 

    %radio button group to select the type of data input          
    hsel_mode = uibuttongroup('Units','characters',...
        'Title','Choose the type of data do you want to analyze',...
        'Position',[12.5 12.5 55 13]);
        uicontrol('Style','Radio','Units','characters',...
            'String','single image file',...
            'Tag','single image file',...
            'Position',[1 10 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','batch mode',...
            'Tag','batch mode',...
            'Position',[1 8.5 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','frames from a movie saved as separate images in a directory',...
            'Tag','images from a movie in a directory',...
            'Position',[1 7 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','movie in a single file',...
            'Tag','movie in a single file',...
            'Position',[1 5.5 50 2],'parent',hsel_mode);
        uicontrol('Style','Radio','Units','characters',...
            'String','batch movies',...
            'Tag','batch movie',...
            'Position',[1 4 50 2],'parent',hsel_mode);
      
    %Strings that file name must or must not contain for the batch mode:
    hfname_str = uipanel('Units','characters',...
        'Parent',fh,...
        'Title','Optional - batch mode only',...
        'Position',[12.5,4,55,12]);
    
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'String','Name Contains :',...
            'HorizontalAlignment','left',...
            'Position',[2,9,25,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'HorizontalAlignment','left',...
            'String','enter as comma-separated list: e.g.   DAPI   or   cy3,DAPI',...
            'Position',[2,7.5,50,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','edit',...
            'String','',...
            'Tag','inclusionString',...
            'Position',[20,9,25,1.5]);
                    
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'String','Name Does Not Contain (comma-separated list)',...
            'HorizontalAlignment','left',...
            'Position',[2,5,25,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','Text',...
            'HorizontalAlignment','left',...
            'String','enter as comma-separated list: e.g.   DAPI   or   cy3,DAPI',...
            'Position',[2,3.5,50,1.2]);
        uicontrol('Parent',hfname_str,'Units','characters',...
            'Style','edit',...
            'Tag','exclusionString',...
            'String','',...
            'Position',[20,5,25,1.5]);
        uicontrol('Style','Radio','Units','characters',...
            'String','Explore Subfolders',...
            'Tag','recursive',...
            'Position',[2,0.5,25,1.2],'Parent',hfname_str);
        
    set(hsel_mode,'Visible','on');  
    set(hfname_str,'Visible','on'); 
    set(fh,'Visible','on');
    
    %next button
    hnext = uicontrol('Parent',fh,'Units','characters',...
                        'Style','pushbutton',...
                        'String','next',...
                        'Position',[47.5,1,20,2]);
    %cancel button
    hcancel = uicontrol('Parent',fh,'Units','characters',...
                        'Style','pushbutton',...
                        'String','cancel',...
                        'Position',[12.5,1,20,2]);
    handles = guihandles(fh);
    set(hnext,'Callback',{@get_mode,fh,hsel_mode});                
    set(hcancel,'Callback',{@cancel,fh});                

%% nested callback function
    function get_mode(src,eventdata,fh,hsel_mode)
        
        xtag = get(get(hsel_mode,'SelectedObject'), 'Tag');

        if strcmp(xtag,'single image file')
            params.fileProcessingMode = 'singleFile'; 
        elseif strcmp(xtag,'batch mode')
            params.fileProcessingMode = 'batch';
        elseif strcmp(xtag,'images from a movie in a directory')
            params.fileProcessingMode = 'movieInDir';
        elseif strcmp(xtag,'movie in a single file')
            params.fileProcessingMode = 'singleFileMovie'; 
        elseif strcmp(xtag,'batch movies')
            params.fileProcessingMode = 'batchMovie'; 
        end
        
        if contains(params.fileProcessingMode,'batch')
            params.inclusionString = get(handles.inclusionString, 'String');
            params.exclusionString = get(handles.exclusionString, 'String');
            if get(handles.recursive, 'Value') == 1
                params.recursive = 1;
            else
                params.recursive = 0;
            end
        end
        if contains(params.fileProcessingMode,'movie') ...
                || contains(params.fileProcessingMode,'Movie')
            params.movieFrameUsedToSetParameters = 1;
        end
        
        uiresume;
    end
    
%% nested callback function
    function cancel(src,eventdata,fh)
        uiresume;
        params.fileProcessingMode = 'cancel';
    end
    
    %% housepkeeping
    uiwait;
    close(fh);
    clear('hnext','hsel_mode','hcancel','u1','u2','fh');
    return   
end